image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      docker run -v /workspace/supervisor-bug/:/data alpine sh -c "touch /data/root-file.empty"

  - command: |
      cat /workspace/supervisor-bug/root-file.empty
