image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      sudo echo "empty" > /workspace/supervisor-bug/root-file.empty
      sudo chown root /workspace/supervisor-bug/root-file.empty
  - command: |
      cat /workspace/supervisor-bug/root-file.empty
